### ISSUE TITLE
你好，请教一个小白的问题

### ISSUE THREAD

**Issue by zhuyunhe** [MeCKodo/vue-tutorial#1]
使用vue-cli把工程搭起来后，使用`npm run dev`运行应用，但此时打开根目录下的index.html是这个样子
![image](https://cloud.githubusercontent.com/assets/10432640/14878116/11168cee-0d54-11e6-8740-6db59fdf3920.png)
`built files will be auto injected`－built文件会自动注入怎么理解呢，我用chrome调试看到这个文件
![image](https://cloud.githubusercontent.com/assets/10432640/14878177/73522490-0d54-11e6-93b3-8b6ae8f4026c.png)
这个app.js文件在哪呢？
意思是.src/main.js这个js文件会被编译成app.js然后自动引入到这？

**Comment by MeCKodo** [comment]
http://www.meckodo.com/?p=721
这是webpack的内存编译，npm run build后会生成线上用的html，会注入相应的文件

**Comment by zhuyunhe** [comment]
@MeCKodo 嗯，谢谢，明白一点了。webpack初学呃
