### ISSUE TITLE
第二次添加时用户信息没有了，如图像，名字，具体请看控制台的错误提示

### ISSUE THREAD

**Issue by bluesky4485** [MeCKodo/vue-tutorial#2]
在LogTime.vue的script段，最后置空的代码` this.timeEntry = {}`有点不妥的吧，这样第一次添加user对象是有的，但是第二次添加时uesr对象没了，js控制台有错误提示的，timeEntry.user.name这类的都取不到 不到了的。

这块应该还是要设置下timeEntry 的user属性的默认值的吧。

另外，期待楼主尽快更新剩下的部分。

**Comment by MeCKodo** [comment]
已更新，这部分留给大家作业。
