### ISSUE TITLE
关于Actions和Mutations

### ISSUE THREAD

**Issue by deepred5** [MeCKodo/vue-tutorial#24]
为什么不直接使用Mutations改变数据，而要Actions包装一下，再发送Mutations
官网说Actions适用于异步操作，但是在本例子里面，并没有异步操作，所以直接用Mutations就可以了吧？
还有，例子里面发送的数据都是字符串，要自己用parseInt转换一下才行

**Comment by MeCKodo** [comment]
我觉得像你这么聪明的前端根本不用看我写的这个渣文章

**Comment by deepred5** [comment]
嘲讽？

**Comment by MeCKodo** [comment]
实话，我这写的非常基础，比较适合只听说过vue想快速写点东西的，又懒得看文档的人
