### ISSUE TITLE
请注明不是原创

### ISSUE THREAD

**Issue by Saber0517** [MeCKodo/vue-tutorial#3]
https://scotch.io/tutorials/build-a-single-page-time-tracking-app-with-vue-js-part-ii

**Comment by MeCKodo** [comment]
第二部分是原创谢谢

**Comment by Saber0517** [comment]
( ⊙ o ⊙ )是的，但还是加上别人的链接吧

**Comment by MeCKodo** [comment]
如果，你很在意的话，之后我会加载源码里

**Comment by Saber0517** [comment]
好的，thx，感谢开源世界有你 (づ｡◕‿‿◕｡)づ
