### ISSUE TITLE
main.js 中 第一行注释//  XXXXXX为什么必须顶文件头写？// 与XXXX之间必须有空格？

### ISSUE THREAD

**Issue by xixi880928** [MeCKodo/vue-tutorial#5]
我在修改文件后，使用npm run dev编译发现一直报错。检查错误原因居然是这样。这是什么原因导致的呢？
main.js 中 第一行注释//  XXXXXX为什么必须顶文件头写？// 与XXXX之间必须有空格？这是什么原因？

**Comment by MeCKodo** [comment]
估计你有开eslint ，我是把这个关了的。

**Comment by xixi880928** [comment]
是的，我刚才去查看了，是eslint的原因。之前没使用过，所以不知道...
