### ISSUE TITLE
npm install错误

### ISSUE THREAD

**Issue by xixi880928** [MeCKodo/vue-tutorial#6]
之前使用另一台电脑时，使用 cnpm install没有问题。后来，换了电脑之后，node与npm的版本都与之前的电脑一样.node是v5.10.1.npm是v3.8.3版本。npm install其他的也没有问题，只是用在这里，npm install 会卡住，cnpm install会报错：
[Error: Cannot find module '/home/lcw/vue-time-tracker/node_modules/.npminstall/phantomjs-prebuilt/2.1.7/phantomjs-prebuilt/lib/location'] code: 'MODULE_NOT_FOUND' 

使用 npm run dev 可以看到hello vue.js的页面。上面的报错也没有npm-debug.log。

**Comment by jackPanyj** [comment]
可能是网络不好把。一般这个包是用来写测试用的。一般我都是`init`的时候直接跳过不选的。

**Comment by MeCKodo** [comment]
请别用cnpm，cnpm经常有问题
