### ISSUE TITLE
你好，想请教个关于后端路由的问题。

### ISSUE THREAD

**Issue by zphhhhh** [MeCKodo/vue-tutorial#8]
我的项目也是使用的 vue-cli 自动构建的，

我看到 tutorial 中后端路由

``` javascript
app.get('/time', function(req, res, next) {
  // 省略部分代码
  });
});
```

写在了 app.js 中，这样应该是用 node app 启动，而没有使用 npm run dev 这样包含了热更新的开发环境。我想把后端路由写在 dev-server 中却没有生效是什么原因呢？是因为使用了 vue-router 吗？这里的前端路由应该是用来控制页面的，后面路由是用来控制与服务器交互的。但是路由不都是URL吗？

对不起，我是初学者，问题的表达有点乱，谢谢。

**Comment by MeCKodo** [comment]
后端不用写路由控制页面了，只需要展示index就行，路由统一前端控制（vue-router），后端写的全是请求接口即可。

**Comment by zphhhhh** [comment]
问题已解决，再次谢谢！
